apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-service-backend-demo-development
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  project: default
  source:
    repoURL: https://github.com/kameswarab/um-service-repo-demo.git
    targetRevision: development
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
