apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-service-backend-demo
spec:
  selector:
    matchLabels:
      run: master-service-backend-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: master-service-backend-demo
    spec:
      containers:
      - name: master-service-backend-demo
        image: 174284634452.dkr.ecr.ap-south-1.amazonaws.com/demo-app/master-service-backend:1.0
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: master-service-backend-demo
  labels:
    run: master-service-backend-demo
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  type: ClusterIP
  selector:
    run: master-service-backend-demo
